### ISSUE TITLE
[BUG] Can't launch the app

### ISSUE THREAD

**Issue by SiriusVI87** [kleidis/Troppical#30] opened 2024-06-25 13:15 UTC
I get the following error:

![image](https://github.com/kleidis/Troppical/assets/57681669/ab7b7b42-a640-4f57-932e-3a7951031790)

**Comment by Ishan09811** [comment] 2024-06-25 16:46
@SiriusVI87 
We apologise for that issue and can you try this [build](https://github.com/kleidis/Troppical/actions/runs/9666338958)

**Comment by John-Enigma** [comment] 2024-06-26 01:33
Same here, but mine doesn't open because it keeps getting flagged as a false positive by Avast Antivirus.

**Comment by SilentSparrow02** [comment] 2024-07-01 04:07
> @SiriusVI87 We apologise for that issue, can you try this [build](https://github.com/kleidis/Troppical/actions/runs/9666338958)

I am trying the build you suggested but it's still not opening:
![image](https://github.com/kleidis/Troppical/assets/59610509/6b5d2a72-0fba-4668-85c6-1294ded01744)

The full error code is as follows:

`Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 652, in connect
  File "urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
  File "ssl.py", line 455, in wrap_socket
  File "ssl.py", line 1042, in _create
  File "ssl.py", line 1320, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nightly.link', port=443): Max retries exceeded with url: /kleidis/Troppical/workflows/build/master/troppical-windows.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "init_troppical.py", line 67, in <module>
  File "init_troppical.py", line 61, in main
  File "init_troppical.py", line 12, in download_and_launch
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 698, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='nightly.link', port=443): Max retries exceeded with url: /kleidis/Troppical/workflows/build/master/troppical-windows.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
`

**Comment by Ishan09811** [comment] 2024-07-02 09:24
@SiriusVI87 
You are connected to an Internet connection when executing init_troppical ?

**Comment by SiriusVI87** [comment] 2024-07-02 17:44
> @SiriusVI87 You are connected to an Internet connection when executing init_troppical ?

Yes, I am.

**Comment by John-Enigma** [comment] 2024-07-07 14:51
Might I suggest revamping the app with an approach similar to [EzYuzu](https://github.com/amakvana/EzYuzu)?

**Comment by kleidis** [comment] 2024-10-19 22:17
As the app is getting a full rewrtie, im closing this

**Closed** 2024-10-19 22:17 UTC
Labels: bug
